#!/usr/bin/env python3
"""Generate naqsh.png — a seamless Islamic geometric pattern tile for the HUD card.

Drawn from scratch (no stock art) in the classic naqsh vocabulary: eight-petal
rosettes on a diagonal lattice, small nested diamonds between them, and
eight-point stars on the edge midpoints.

Seamlessness: every motif is drawn at all nine tile offsets (-S, 0, +S in both
axes), so anything crossing an edge reappears on the opposite side exactly.

Output is white line-work on transparency; the HUD tints it down via Opacity.
Reproducible — just rerun.
"""
import math
from PIL import Image, ImageDraw

S = 256          # logical tile size
SS = 4           # supersample factor for clean anti-aliasing
N = S * SS       # working canvas

LINE = (255, 255, 255, 255)
LW = max(1, int(1.6 * SS))   # stroke width


def rotate(points, cx, cy, theta):
    ct, st = math.cos(theta), math.sin(theta)
    return [(cx + x * ct - y * st, cy + x * st + y * ct) for x, y in points]


def leaf(cx, cy, theta, r0, r1, halfw, steps=28):
    """One pointed petal: width swells sinusoidally from base to tip."""
    upper, lower = [], []
    for i in range(steps + 1):
        t = i / steps
        d = r0 + (r1 - r0) * t
        w = halfw * math.sin(math.pi * t)
        upper.append((d, w))
        lower.append((d, -w))
    return rotate(upper + lower[::-1], cx, cy, theta)


def rosette(d, cx, cy, scale=1.0):
    """Eight petals around a small centre ring."""
    r0, r1 = 0.10 * S * SS * scale, 0.34 * S * SS * scale
    halfw = 0.085 * S * SS * scale
    for k in range(8):
        pts = leaf(cx, cy, k * math.pi / 4, r0, r1, halfw)
        d.line(pts + [pts[0]], fill=LINE, width=LW, joint="curve")

    r = 0.045 * S * SS * scale
    d.ellipse([cx - r, cy - r, cx + r, cy + r], outline=LINE, width=LW)


def diamond(d, cx, cy, r):
    """A diamond with a smaller one nested inside."""
    for rr in (r, r * 0.45):
        pts = [(cx, cy - rr), (cx + rr, cy), (cx, cy + rr), (cx - rr, cy)]
        d.line(pts + [pts[0]], fill=LINE, width=LW, joint="curve")


def star8(d, cx, cy, outer, inner):
    """Eight-point star: alternating outer and inner radii."""
    pts = []
    for k in range(16):
        rr = outer if k % 2 == 0 else inner
        a = k * math.pi / 8 - math.pi / 2
        pts.append((cx + rr * math.cos(a), cy + rr * math.sin(a)))
    d.line(pts + [pts[0]], fill=LINE, width=LW, joint="curve")


def svg_shapes():
    """Same motifs as the raster tile, in logical units, as SVG primitives."""
    shapes = []

    def poly(pts):
        shapes.append(("poly", pts))

    def leaf_l(cx, cy, theta, r0, r1, halfw, steps=28):
        upper, lower = [], []
        for i in range(steps + 1):
            t = i / steps
            d = r0 + (r1 - r0) * t
            w = halfw * math.sin(math.pi * t)
            upper.append((d, w))
            lower.append((d, -w))
        return rotate(upper + lower[::-1], cx, cy, theta)

    def rosette_l(cx, cy):
        r0, r1, halfw = 0.10 * S, 0.34 * S, 0.085 * S
        for k in range(8):
            poly(leaf_l(cx, cy, k * math.pi / 4, r0, r1, halfw))
        shapes.append(("circle", cx, cy, 0.045 * S))

    def diamond_l(cx, cy, r):
        for rr in (r, r * 0.45):
            poly([(cx, cy - rr), (cx + rr, cy), (cx, cy + rr), (cx - rr, cy)])

    def star8_l(cx, cy, outer, inner):
        pts = []
        for k in range(16):
            rr = outer if k % 2 == 0 else inner
            a = k * math.pi / 8 - math.pi / 2
            pts.append((cx + rr * math.cos(a), cy + rr * math.sin(a)))
        poly(pts)

    def tiled(fn, x, y, *args):
        for dx in (-S, 0, S):
            for dy in (-S, 0, S):
                fn(x + dx, y + dy, *args)

    tiled(rosette_l, 0, 0)
    tiled(rosette_l, S // 2, S // 2)

    q = S // 4
    for (x, y) in ((q, q), (3 * q, q), (q, 3 * q), (3 * q, 3 * q)):
        tiled(diamond_l, x, y, 0.055 * S)

    for (x, y) in ((S // 2, 0), (0, S // 2)):
        tiled(star8_l, x, y, 0.075 * S, 0.032 * S)

    return shapes


def write_svg(path="naqsh.svg", stroke="#D5D2CC", background="#FFFFFF"):
    """Seamless vector tile. Also exposes a <pattern> for tiling in design tools."""
    body = []
    for shape in svg_shapes():
        if shape[0] == "poly":
            pts = shape[1]
            d = "M " + " L ".join(f"{x:.2f},{y:.2f}" for x, y in pts) + " Z"
            body.append(f'      <path d="{d}"/>')
        else:
            _, cx, cy, r = shape
            body.append(f'      <circle cx="{cx:.2f}" cy="{cy:.2f}" r="{r:.2f}"/>')
    marks = "\n".join(body)

    svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{S}" height="{S}"
     viewBox="0 0 {S} {S}">
  <title>Naqsh tile — seamless Islamic geometric pattern</title>
  <desc>Generated by make_naqsh.py. Tiles seamlessly at {S}x{S}.</desc>
  <defs>
    <clipPath id="tile">
      <rect x="0" y="0" width="{S}" height="{S}"/>
    </clipPath>
    <g id="marks" fill="none" stroke="{stroke}" stroke-width="1.6"
       stroke-linejoin="round" stroke-linecap="round">
{marks}
    </g>
    <pattern id="naqsh" width="{S}" height="{S}" patternUnits="userSpaceOnUse">
      <use href="#marks" clip-path="url(#tile)"/>
    </pattern>
  </defs>
  <rect width="{S}" height="{S}" fill="{background}"/>
  <use href="#marks" clip-path="url(#tile)"/>
</svg>
'''
    with open(path, "w", encoding="utf-8") as f:
        f.write(svg)
    print(f"wrote {path}")


def build():
    img = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    T = N  # tile span in working pixels

    def tiled(fn, x, y, *args):
        """Draw at every wrap offset so the tile joins seamlessly."""
        for dx in (-T, 0, T):
            for dy in (-T, 0, T):
                fn(d, x + dx, y + dy, *args)

    # Rosettes on a diagonal lattice: tile corners and centre.
    tiled(lambda dd, x, y: rosette(dd, x, y), 0, 0)
    tiled(lambda dd, x, y: rosette(dd, x, y), T // 2, T // 2)

    # Nested diamonds in the gaps between rosettes.
    q = T // 4
    for (x, y) in ((q, q), (3 * q, q), (q, 3 * q), (3 * q, 3 * q)):
        tiled(diamond, x, y, 0.055 * T)

    # Eight-point stars on the edge midpoints.
    for (x, y) in ((T // 2, 0), (0, T // 2)):
        tiled(star8, x, y, 0.075 * T, 0.032 * T)

    tile = img.resize((S, S), Image.LANCZOS)
    tile.save("naqsh.png")
    print("wrote naqsh.png")


if __name__ == "__main__":
    build()
    write_svg()
